import type { FoodCatalogEntry } from '../types/catalog'

export const VERIFIED_CATALOG_ENTRIES = [
  {
    id: 'spaghetti-cotti-al-dente', nome: 'Spaghetti cotti al dente', sinonimi: [], categoria: 'Cereali e derivati', sottocategoria: 'Pasta', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 180, unita_misura: 'g', energia_kcal: 158, carboidrati_totali_g: 30.86, zuccheri_g: 0.56, fibre_g: 1.8, carboidrati_disponibili_g: 29.06, carboidrati_disponibili_porzione_g: 52.3, proteine_g: 5.8, grassi_totali_g: 0.93, grassi_saturi_g: 0.18, sodio_mg: 1, ig_min: 44, ig_medio: 48, ig_max: 55, ig_affidabilita: 'alta', carico_glicemico_porzione: 25.1, formula_cg: '48 * (29.06 g/100g * 180 g / 100) / 100 = 25.1', fascia_impatto: 'alto', fonte_macro: 'USDA FoodData Central', fonte_macro_descrizione: 'Pasta, cooked, enriched, without added salt', fonte_macro_fdcId: 169737, fonte_macro_dataType: 'SR Legacy', fonte_ig: 'International Tables of GI/GL (Diabetes Care)', ig_da_verificare: true, tipo_dato_macro: 'ufficiale', tipo_dato_ig: 'stimato_letteratura', data_aggiornamento: '2026-07-22', stato_editoriale: 'rivisto', revisione: { da: 'Analisi AI (metodo: confronto con tabelle internazionali GI/GL)', data: '2026-07-23', esito: 'confermato', nota: 'IG 48: corretto per cottura al dente. Confermato.' },
  },
  {
    id: 'guanciale', nome: 'Guanciale', sinonimi: [], categoria: 'Carne', sottocategoria: 'Salumi e insaccati', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 30, unita_misura: 'g', energia_kcal: 655, carboidrati_totali_g: 0, zuccheri_g: 0, fibre_g: 0, carboidrati_disponibili_g: 0, carboidrati_disponibili_porzione_g: 0, proteine_g: 8, grassi_totali_g: 70, grassi_saturi_g: 25, sodio_mg: 1500, ig_min: null, ig_medio: null, ig_max: null, ig_affidabilita: 'n/a', carico_glicemico_porzione: null, formula_cg: 'IG non applicabile (carboidrati trascurabili)', fascia_impatto: 'trascurabile', fonte_macro: 'Stima (tabelle di composizione)', fonte_macro_descrizione: 'Valori stimati (tabelle di composizione alimenti)', fonte_macro_fdcId: null, fonte_macro_dataType: 'stimato', fonte_ig: null, ig_da_verificare: false, tipo_dato_macro: 'stimato', tipo_dato_ig: 'non_applicabile', data_aggiornamento: '2026-07-22', stato_editoriale: 'bozza', revisione: null,
  },
  {
    id: 'uovo-crudo-intero', nome: 'Uovo crudo intero', sinonimi: [], categoria: 'Uova', sottocategoria: 'Uova', origine_geografica: 'Internazionale', lingua: 'it', porzione_standard_g: 50, unita_misura: 'g', energia_kcal: 143, carboidrati_totali_g: 0.72, zuccheri_g: 0.37, fibre_g: 0, carboidrati_disponibili_g: 0.72, carboidrati_disponibili_porzione_g: 0.4, proteine_g: 12.56, grassi_totali_g: 9.51, grassi_saturi_g: 3.13, sodio_mg: 142, ig_min: null, ig_medio: null, ig_max: null, ig_affidabilita: 'n/a', carico_glicemico_porzione: null, formula_cg: 'IG non applicabile (carboidrati trascurabili)', fascia_impatto: 'trascurabile', fonte_macro: 'USDA FoodData Central', fonte_macro_descrizione: 'Egg, whole, raw, fresh', fonte_macro_fdcId: 171287, fonte_macro_dataType: 'SR Legacy', fonte_ig: null, ig_da_verificare: false, tipo_dato_macro: 'ufficiale', tipo_dato_ig: 'non_applicabile', data_aggiornamento: '2026-07-22', stato_editoriale: 'bozza', revisione: null,
  },
  {
    id: 'pecorino-romano', nome: 'Pecorino romano', sinonimi: [], categoria: 'Latticini', sottocategoria: 'Formaggi', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 30, unita_misura: 'g', energia_kcal: 387, carboidrati_totali_g: 3.63, zuccheri_g: 0.73, fibre_g: 0, carboidrati_disponibili_g: 3.63, carboidrati_disponibili_porzione_g: 1.1, proteine_g: 31.8, grassi_totali_g: 26.94, grassi_saturi_g: 17.11, sodio_mg: 1433, ig_min: null, ig_medio: null, ig_max: null, ig_affidabilita: 'n/a', carico_glicemico_porzione: null, formula_cg: 'IG non applicabile (carboidrati trascurabili)', fascia_impatto: 'trascurabile', fonte_macro: 'USDA FoodData Central', fonte_macro_descrizione: 'Cheese, romano', fonte_macro_fdcId: 171249, fonte_macro_dataType: 'SR Legacy', fonte_ig: null, ig_da_verificare: false, tipo_dato_macro: 'ufficiale', tipo_dato_ig: 'non_applicabile', data_aggiornamento: '2026-07-22', stato_editoriale: 'bozza', revisione: null,
  },
  {
    id: 'passata-di-pomodoro', nome: 'Passata di pomodoro', sinonimi: [], categoria: 'Salse e condimenti', sottocategoria: 'Salse', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 100, unita_misura: 'g', energia_kcal: 32, carboidrati_totali_g: 6, zuccheri_g: 4.5, fibre_g: 1.5, carboidrati_disponibili_g: 4.5, carboidrati_disponibili_porzione_g: 4.5, proteine_g: 1.4, grassi_totali_g: 0.3, grassi_saturi_g: 0.05, sodio_mg: 15, ig_min: 30, ig_medio: 35, ig_max: 40, ig_affidabilita: 'bassa', carico_glicemico_porzione: 1.6, formula_cg: '35 * (4.5 g/100g * 100 g / 100) / 100 = 1.6', fascia_impatto: 'basso', fonte_macro: 'Stima (tabelle di composizione)', fonte_macro_descrizione: 'Valori stimati (tabelle di composizione alimenti)', fonte_macro_fdcId: null, fonte_macro_dataType: 'stimato', fonte_ig: 'International Tables of GI/GL (Diabetes Care)', ig_da_verificare: true, tipo_dato_macro: 'stimato', tipo_dato_ig: 'stimato_letteratura', data_aggiornamento: '2026-07-22', stato_editoriale: 'rivisto', revisione: { da: 'Analisi AI (metodo: confronto con tabelle internazionali GI/GL)', data: '2026-07-23', esito: 'confermato', nota: 'IG 35: coerente col pomodoro. Confermato.' },
  },
  {
    id: 'mozzarella', nome: 'Mozzarella', sinonimi: [], categoria: 'Latticini', sottocategoria: 'Formaggi', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 50, unita_misura: 'g', energia_kcal: 299, carboidrati_totali_g: 2.4, zuccheri_g: 0, fibre_g: 0, carboidrati_disponibili_g: 2.4, carboidrati_disponibili_porzione_g: 1.2, proteine_g: 22.17, grassi_totali_g: 22.14, grassi_saturi_g: 13.9, sodio_mg: 486, ig_min: null, ig_medio: null, ig_max: null, ig_affidabilita: 'n/a', carico_glicemico_porzione: null, formula_cg: 'IG non applicabile (carboidrati trascurabili)', fascia_impatto: 'trascurabile', fonte_macro: 'USDA FoodData Central', fonte_macro_descrizione: 'Cheese, mozzarella, whole milk', fonte_macro_fdcId: 170845, fonte_macro_dataType: 'SR Legacy', fonte_ig: null, ig_da_verificare: false, tipo_dato_macro: 'ufficiale', tipo_dato_ig: 'non_applicabile', data_aggiornamento: '2026-07-22', stato_editoriale: 'bozza', revisione: null,
  },
  {
    id: 'pizza-margherita', nome: 'Pizza margherita', sinonimi: [], categoria: 'Cereali e derivati', sottocategoria: 'Piatti', origine_geografica: 'Italia', lingua: 'it', porzione_standard_g: 250, unita_misura: 'g', energia_kcal: 280, carboidrati_totali_g: 29.93, zuccheri_g: 3.21, fibre_g: 1.7, carboidrati_disponibili_g: 28.23, carboidrati_disponibili_porzione_g: 70.6, proteine_g: 11.73, grassi_totali_g: 12.56, grassi_saturi_g: 5.18, sodio_mg: 624, ig_min: 36, ig_medio: 60, ig_max: 80, ig_affidabilita: 'media', carico_glicemico_porzione: 42.4, formula_cg: '60 * (28.23 g/100g * 250 g / 100) / 100 = 42.4', fascia_impatto: 'alto', fonte_macro: 'USDA FoodData Central', fonte_macro_descrizione: 'PIZZA HUT 12" Cheese Pizza, Pan Crust', fonte_macro_fdcId: 172041, fonte_macro_dataType: 'SR Legacy', fonte_ig: 'International Tables of GI/GL (Diabetes Care)', ig_da_verificare: true, tipo_dato_macro: 'ufficiale', tipo_dato_ig: 'stimato_letteratura', data_aggiornamento: '2026-07-22', stato_editoriale: 'stima', revisione: { da: 'Analisi AI (metodo: confronto con tabelle internazionali GI/GL)', data: '2026-07-23', esito: 'stima', nota: 'Stima: l’IG della pizza varia molto (impasto, condimenti); ~60 indicativo. Macro USDA da pizza generica al formaggio.' },
  },
] as const satisfies readonly FoodCatalogEntry[]
